server:
  port: 9002
spring:
  application:
    name: produce
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    publisher-returns: true  #开始失败返回
    publisher-confirm-type: correlated #事物模式 降低吞吐量？
    listener:
      simple:
        acknowledge-mode: auto #开启ack
      direct:
        acknowledge-mode: auto
    template: #支持消息的确认返回
      mandatory: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
rocketmq:
  name-server: 119.3.126.204:9876
  producer:
    group: group
    send-message-timeout: 300000
    max-message-size: 4096 # 最大消息发送次数 默认 1024*4 4M
    retry-times-when-send-failed: 4 # 发送失败重试次数 默认 2

