#zuul:
#  host:
#    socket-timeout-millis: 15000
#    connect-timeout-millis: 60000
#  force-original-query-string-encoding: true
#  routes:
#    clientMajor:
#      path: /deagle/major/**
#      sensitiveHeaders:
#      service-id: clientMajor
#  ribbon-isolation-strategy: SEMAPHORE
#  semaphore:
#    max-semaphores: 20
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 90000
#ribbon:
#  eager-load:
#    enabled: true
#    clients: clientMajor
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB
#zuul:
#  host:
#    connect-timeout-millis: 300000
#    socket-timeout-millis: 100000
#    connection-request-timeout-millis: 100000
#    time-to-live: 10000