zuul:
  host:
    socket-timeout-millis: 15000
    connect-timeout-millis: 60000
  force-original-query-string-encoding: true
  routes:
    oauth:
      service-id: oauth
      path: /oauth/major/**

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 1000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#  ignored-services: '*' 禁止通过服务名称访问
#  prefix: 'deagle' 设置前缀



#  ribbon-isolation-strategy: SEMAPHORE
#  semaphore:
#    max-semaphores: 20
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 90000
#ribbon:
#  eager-load:
#    enabled: true
#    clients: clientMajor