eureka:
  client:
    fetch-registry: false #单点不缓存
    register-with-eureka: false #单点不注册
    # 配置其他eureka的地址，如果多台则逗号分隔。
    # defaultZone: http://${security.user.name}:${security.user.password}@10.13.22.19:${server.port}/eureka
    registry-fetch-interval-seconds: 5 #定时刷新本地缓存时间
    service-url:
      defaultZone: http://eureka.server.deagle:${server.port}/eureka/
  server:
    enable-self-preservation: false #为true 五分钟内心跳低于85%的 也不剔除该服务
    renewal-percent-threshold: 0.85 # 默认五分钟内心跳数低于85%则 剔除该服务
    response-cache-update-interval-ms: 3000 #
#    renewal-threshold-update-interval-ms: 120000 # 心跳阈值计算周期 开启自我保护，可以改这个配置
    eviction-interval-timer-in-ms: 500000 #主动失效检测时间
    use-read-only-response-cache: false
#  instance:
    lease-renewal-interval-in-seconds: 5 #心跳间隔
    hostname: http://localhost:1000/eureka/


