spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_seata?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 500
      phy-timeout-millis: 7200000
      remove-abandoned: true
      remove-abandoned-timeout: 180
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      validation-query: SELECT 1
      validation-query-timeout: 1
      time-between-eviction-runs-millis: 15000
      default-auto-commit: true
      log-abandoned: false
      connection-properties: socketTimeout=300000;connectTimeout=100000
redisson:
  address: redis://127.0.0.1:6379
# seata
seata:
  tx-service-group: deagle_at
  service:
    grouplist: 127.0.0.1:8091
logging:
  level:
    io:
      seata: info
      samples:
        account:
          persistence:
            AccountMapper: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.zw.**
  type-aliases-super-type: java.lang.Object
  type-enums-package: com.baomidou.mybatisplus.samples.quickstart.enums
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    aggressive-lazy-loading: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: FAILING
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      table-underline: true
      id-type: auto

ribbon:
  readTimeout: 30000
  socketTimeout: 30000
  connectTimeout: 30000
feign:
  hystrix:
    enabled: false
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
          timeout:
            enabled: false