server:
  port: 9003
spring:
  application:
    name: consumer
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
      direct:
        acknowledge-mode: auto
rocketmq:
  name-server: 119.3.126.204:9876
