#spring:
#  profiles:
#    active: dev
#  application:
#    name: primary
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: public
#        group: deagle
##        name: deagle-primary-dev  # data-id  ${prefix}-${spring.profile.active}.${file-extension}
#        file-extension: yml
#        refresh-enabled: true
#
#server:
#  port: 1200
##  原本启动参数： --spring.profiles.active=dev
##  需要替换参数为：--spring.cloud.nacos.config.namespace=43cfdf88-1a5e